export const autoImportConfig = [
  {
    "@dfds-ui/navaigator": [
      // Skipped due to DOM/Web API global name conflicts:
      //   Text          — clashes with DOM `Text` interface
      //   Notification  — clashes with the `Notification` Web API
      // Import these explicitly when needed.

      // Buttons & links
      "Button",
      "ToggleButton",
      "InlineLink",

      // Form inputs
      "TextInput",
      "TextArea",
      "Autocomplete",
      "DatePicker",
      "MultiSelect",
      "NumberStepper",
      "PhoneNumberInput",
      "SelectInput",
      "Switch",
      "Checkbox",
      "CheckboxGroup",
      "RadioGroup",
      "RadioGroupItem",

      // Select
      "Select",
      "SelectContent",
      "SelectField",
      "SelectGroup",
      "SelectItem",
      "SelectLabel",
      "SelectSeparator",
      "SelectTrigger",

      // Feedback
      "Badge",
      "Chip",
      "LoadingSpinner",
      "Skeleton",
      "Toaster",
      "toast",

      // Surfaces & layout
      "Card",
      "CardCategory",
      "CardContent",
      "CardDescription",
      "CardFooter",
      "CardHeader",
      "CardImage",
      "CardMeta",
      "CardOverlay",
      "CardTitle",
      "Separator",
      "Surface",

      // Overlays
      "Dialog",
      "DialogBody",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogTitle",
      "DialogTrigger",
      "Drawer",
      "DrawerBody",
      "DrawerClose",
      "DrawerContent",
      "DrawerDescription",
      "DrawerFooter",
      "DrawerHeader",
      "DrawerTitle",
      "DrawerTrigger",
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger",
      "Tooltip",
      "TooltipContent",
      "TooltipProvider",
      "TooltipTrigger",

      // Navigation
      "Accordion",
      "AccordionContent",
      "AccordionGroupHeading",
      "AccordionItem",
      "AccordionTrigger",
      "Pagination",
      "PaginationContent",
      "PaginationEllipsis",
      "PaginationItem",
      "PaginationLink",
      "PaginationNext",
      "PaginationPrevious",
      "Tabs",
      "TabsContent",
      "TabsList",
      "TabsTrigger",

      // Data display
      "DescriptionList",
      "DescriptionListItem",
      "DescriptionTerm",
      "DescriptionDetail",
      "List",
      "ListItem",
      "Table",
      "TableBody",
      "TableCaption",
      "TableCell",
      "TableFooter",
      "TableHead",
      "TableHeader",
      "TableRow",

      // Utilities
      "cn",
    ],
  },
  {
    react: [
      "cacheSignal",
      "createRef",
      "createContext",
      "forwardRef",
      "Activity",
      "Fragment",
      "Suspense",
      "useCallback",
      "useContext",
      "useDebugValue",
      "useDeferredValue",
      "useEffect",
      "useEffectEvent",
      "useId",
      "useImperativeHandle",
      "useInsertionEffect",
      "useLayoutEffect",
      "useMemo",
      "useReducer",
      "useRef",
      "useState",
      "useSyncExternalStore",
      "useTransition",
      "useActionState",
      "useOptimistic",
    ],
  },
  {
    "@/components/generic/StatusBadge": [
      "StatusBadge",
      "STATUS_META",
      "BOOKING_STATUSES",
    ],
  },
  {
    "@hookform/resolvers/zod": ["zodResolver"],
  },
  {
    "@dfds-ui/navaigator/shared/field": ["FieldError", "FieldLabel"],
  },
  {
    "@tanstack/react-router": ["Link", "useNavigate", "getRouteApi"],
  },
];
